### ISSUE TITLE
OAuth config startup problem

### ISSUE THREAD

**Issue by fmarani** [jhuapl-boss/boss-oidc#11]
I am following roughly this tutorial to setup this library: http://blog.jonharrington.org/static/integrate-django-with-keycloak/

The following exception happens when I run any manage.py command:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/local/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/code/manage.py", line 3, in <module>
    """
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/openplan/urls.py", line 66, in <module>
    path('openid/', include('djangooidc.urls')),
  File "/usr/local/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/djangooidc/urls.py", line 4, in <module>
    from . import views
  File "/usr/local/lib/python3.6/site-packages/djangooidc/views.py", line 21, in <module>
    CLIENTS = OIDCClients(settings)
  File "/usr/local/lib/python3.6/site-packages/djangooidc/oidc.py", line 148, in __init__
    self.client[key] = self.create_client(**val)
  File "/usr/local/lib/python3.6/site-packages/djangooidc/oidc.py", line 177, in create_client
    behaviour=kwargs["behaviour"], verify_ssl=verify_ssl, **args)
  File "/usr/local/lib/python3.6/site-packages/djangooidc/oidc.py", line 31, in __init__
    client_authn_method, keyjar, verify_ssl)
  File "/usr/local/lib/python3.6/site-packages/oic/oic/__init__.py", line 335, in __init__
    config=config, client_cert=client_cert)
  File "/usr/local/lib/python3.6/site-packages/oic/oauth2/__init__.py", line 212, in __init__
    self.issuer = self.config['issuer']
TypeError: 'bool' object is not subscriptable
```

I think because the number of arguments mismatch.

**Comment by derek-pryor** [comment]
Created jhuapl-boss/django-oidc#5 to fix this issue
