### ISSUE TITLE
 File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__     return self._session[key] KeyError: 'op'

### ISSUE THREAD

**Issue by Allan-Nava** [jhuapl-boss/boss-oidc#12]
Hi @derek-pryor, 
I have this error:

```
Internal Server Error: /openid/callback/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/djangooidc/views.py", line 86, in authz_cb
    client = CLIENTS[request.session["op"]]
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__
    return self._session[key]
KeyError: 'op'
[26/Feb/2018 13:46:36] "GET /openid/callback/login/?state=eIPh2qXLAPTD6Bxl&code=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..VoGhtcibjd4qDx-fZgSWXw.7MqJc8VZ5kuwikVy0DINPd6C1fF9A0DzGOVVBw04nXpr9YRx91jPPREVxOxmtHVTEq562MoZ7WfElONtiiIcZRTtvd1J5WwHfB03SJa9iMSRl4BT_8__1oRrL7LKDKIkAuNNVAl-ghBUzM4dZbakuolCSPFZtQqMGA8Z4G8J0XA0JZv26Gimia60l4u8SyRx0-2K-lGyyz4RsQBVR4DJnxPtjiO-Go2MYEosoJV97J12FiwTJO_KVdjPurEm6m9w.lBk19XAq1Pqhmb7FIKGnAw HTTP/1.1" 500 76190

```

**Comment by k-dahl** [comment]
This seems to have something to do with Django 2.0, when I switched to 1.11 it worked fine for me.

**Comment by mbourqui** [comment]
I have this issue as well on Django 1.11.12. It occurs after users register on a Keycloak server, when they are redirected back to my website on the Keycloack registration process termination.
It also occurs on regular login.

**Comment by to-bee** [comment]
That happens when you run Django on 127.0.0.1:8000 and you set the redirect url to localhost:8000. Just open Django on localhost:8000 and it works.

**Comment by Allan-Nava** [comment]
@to-bee i use dns but I still have the same error

**Comment by mbourqui** [comment]
It occurs on one of my website on production, and an other website using version 0.1 does not suffer this issue.
